ip = "127.0.0.1"
port = 8080
method = "roundrobin"

[[servers]]
ip = "localhost"
port = 1232

[[servers]]
ip = "localhost"
port = 1233

[[servers]]
ip = "localhost"
port = 1234

[health_check]
port = 8080
timeout = 10
interval = 5
healthy_threshold = 10
unhealthy_threshold = 10