ip = "127.0.0.1"
port = 8080
strategy = "RoundRobin"

[[servers]]
ip = "http://httpbin.org/ip"
port = 80

[[servers]]
ip = "http://httpbin.org/ip"
port = 80

[[servers]]
ip = "http://httpbin.org/ip"
port = 80

[health_check]
port = 8080
timeout = 10
interval = 5
healthy_threshold = 10
unhealthy_threshold = 10