ip = "127.0.0.1"
port = 8080
strategy = "RoundRobin"

[[servers]]
ip = "3.220.112.94"
port = 80
path = "/ip"

[[servers]]
ip = "3.220.112.94"
port = 80
path = "/ip"

[[servers]]
ip = "3.220.112.94"
port = 80
path = "/ip"

[health_check]
port = 8080
timeout = 10
interval = 5
healthy_threshold = 10
unhealthy_threshold = 10